[mypy]
python_version = 3.11
ignore_missing_imports = True
show_error_codes = True
pretty = True
warn_unused_ignores = True

exclude = (.*_backup.*\.py$|rag_api\.py$|models\.py$|rag\.py$|document[\\/]router\.py$|document[\\/]service\.py$|document[\\/]parser\.py$)